(function(){
"use strict";
var STORAGE_KEY="benefitBookmarks",data=Array.isArray(window.BENEFITS_DATA)?window.BENEFITS_DATA:[],validIds=new Set(data.map(function(b){return b.id}));
function read(){try{var value=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");if(!Array.isArray(value))return[];return value.filter(function(id,index,array){return typeof id==="string"&&validIds.has(id)&&array.indexOf(id)===index})}catch(error){return[]}}
function write(ids){var clean=ids.filter(function(id,index,array){return validIds.has(id)&&array.indexOf(id)===index});try{localStorage.setItem(STORAGE_KEY,JSON.stringify(clean));document.dispatchEvent(new CustomEvent("benefitbookmarkschange",{detail:{ids:clean.slice()}}));return true}catch(error){announce("브라우저 저장소를 사용할 수 없어 즐겨찾기를 변경하지 못했습니다.");return false}}
function has(id){return read().indexOf(id)!==-1}
function add(id){if(!validIds.has(id))return false;var ids=read().filter(function(value){return value!==id});ids.unshift(id);return write(ids)}
function remove(id){return write(read().filter(function(value){return value!==id}))}
function toggle(id){return has(id)?remove(id):add(id)}
function clear(){return write([])}
function benefit(id){return data.find(function(item){return item.id===id})||null}
function announce(message){var live=document.getElementById("bookmarkGlobalLive");if(!live){live=document.createElement("p");live.id="bookmarkGlobalLive";live.className="bookmark-sr-live";live.setAttribute("aria-live","polite");document.body.appendChild(live)}live.textContent="";setTimeout(function(){live.textContent=message},10)}
function button(id,extraClass){var saved=has(id),b=document.createElement("button");b.type="button";b.className="bookmark-toggle "+(extraClass||"");b.dataset.bookmarkId=id;b.setAttribute("aria-pressed",String(saved));b.setAttribute("aria-label",(saved?"즐겨찾기에서 삭제: ":"즐겨찾기에 저장: ")+(benefit(id)||{}).title);b.innerHTML='<span aria-hidden="true">'+(saved?"⭐":"☆")+'</span><span class="bookmark-button-text">'+(saved?"저장됨":"즐겨찾기")+'</span>';return b}
function updateButtons(){document.querySelectorAll(".bookmark-toggle[data-bookmark-id]").forEach(function(b){var item=benefit(b.dataset.bookmarkId),saved=has(b.dataset.bookmarkId);b.setAttribute("aria-pressed",String(saved));b.setAttribute("aria-label",(saved?"즐겨찾기에서 삭제: ":"즐겨찾기에 저장: ")+(item?item.title:"지원정보"));b.querySelector("[aria-hidden]").textContent=saved?"⭐":"☆";var text=b.querySelector(".bookmark-button-text");if(text)text.textContent=saved?"저장됨":"즐겨찾기"})}
function idFromArticle(article){var link=article.querySelector('a[href]');if(!link)return null;var file=(link.getAttribute("href")||"").split(/[?#]/)[0].split("/").pop();var item=data.find(function(b){return b.url===file});return item?item.id:null}
function enhance(root){(root||document).querySelectorAll("article:not([data-bookmark-ready])").forEach(function(article){if(article.classList.contains("bookmark-result-card"))return;var id=idFromArticle(article);if(!id)return;article.dataset.bookmarkReady="true";article.classList.add("bookmark-card-host");article.insertBefore(button(id,"bookmark-card-button"),article.firstChild)})}
function enhanceDetail(){var file=location.pathname.split("/").pop()||"index.html",item=data.find(function(b){return b.url===file});if(!item||document.querySelector(".bookmark-detail-button"))return;var host=document.querySelector("main")||document.body,wrap=document.createElement("div");wrap.className="bookmark-detail-action";wrap.appendChild(button(item.id,"bookmark-detail-button"));host.insertBefore(wrap,host.firstChild)}
document.addEventListener("click",function(event){var target=event.target.closest(".bookmark-toggle[data-bookmark-id]");if(!target)return;var item=benefit(target.dataset.bookmarkId),wasSaved=has(target.dataset.bookmarkId);if(toggle(target.dataset.bookmarkId)){updateButtons();announce((item?item.title:"지원정보")+(wasSaved?" 즐겨찾기를 삭제했습니다.":" 즐겨찾기에 저장했습니다."));target.classList.remove("is-animating");void target.offsetWidth;target.classList.add("is-animating")}});
document.addEventListener("benefitbookmarkschange",updateButtons);
function init(){enhance(document);enhanceDetail();new MutationObserver(function(records){records.forEach(function(record){record.addedNodes.forEach(function(node){if(node.nodeType===1)enhance(node.matches&&node.matches("article")?node.parentNode:node)})})}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
/* Future extension point: connect member accounts, login, and cloud synchronization here. It is intentionally unused in this local-only version. */
function syncBookmarks(){return Promise.resolve(read())}
window.BenefitBookmarks={key:STORAGE_KEY,get:read,has:has,add:add,remove:remove,toggle:toggle,clear:clear,benefit:benefit,enhance:enhance,syncBookmarks:syncBookmarks};
}());

(function(){
"use strict";
if(!document.getElementById("bookmarkList"))return;
var api=window.BenefitBookmarks,data=Array.isArray(window.BENEFITS_DATA)?window.BENEFITS_DATA:[],query=document.getElementById("bookmarkSearch"),sort=document.getElementById("bookmarkSort"),category=document.getElementById("bookmarkCategory"),region=document.getElementById("bookmarkRegion"),list=document.getElementById("bookmarkList"),empty=document.getElementById("bookmarkEmpty"),count=document.getElementById("bookmarkCount"),live=document.getElementById("bookmarkPageLive"),clearButton=document.getElementById("bookmarkClear");
function escapeHtml(v){return String(v||"").replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function options(select,values){values.filter(Boolean).filter(function(v,i,a){return a.indexOf(v)===i}).sort(function(a,b){return a.localeCompare(b,"ko-KR")}).forEach(function(value){var option=document.createElement("option");option.value=value;option.textContent=value;select.appendChild(option)})}
function normalize(v){return String(v||"").toLocaleLowerCase("ko-KR").replace(/\s+/g,"")}
function current(){var ids=api.get(),items=ids.map(api.benefit).filter(Boolean),q=normalize(query.value);items=items.filter(function(b){return(!q||normalize([b.title,b.summary,b.category,b.region,b.district,(b.keywords||[]).join(" ")].join(" ")).indexOf(q)!==-1)&&(!category.value||b.category===category.value)&&(!region.value||b.region===region.value)});if(sort.value==="name")items.sort(function(a,b){return a.title.localeCompare(b.title,"ko-KR")});if(sort.value==="category")items.sort(function(a,b){return a.category.localeCompare(b.category,"ko-KR")||a.title.localeCompare(b.title,"ko-KR")});if(sort.value==="region")items.sort(function(a,b){return(a.district||a.region).localeCompare(b.district||b.region,"ko-KR")||a.title.localeCompare(b.title,"ko-KR")});return items}
function card(b){return'<article class="bookmark-result-card"><button type="button" class="bookmark-remove" data-remove-id="'+escapeHtml(b.id)+'" aria-label="즐겨찾기에서 삭제: '+escapeHtml(b.title)+'">삭제</button><div class="bookmark-result-badges"><span>'+escapeHtml(b.category)+'</span><span>'+escapeHtml(b.district||b.region)+'</span><span>'+escapeHtml(b.applicationStatus||"공고 확인")+'</span></div><h2>'+escapeHtml(b.title)+'</h2><p>'+escapeHtml(b.summary||"정보 없음")+'</p>'+(b.url?'<a href="'+encodeURI(b.url)+'">자세히 보기</a>':'<span>상세페이지 정보 없음</span>')+'</article>'}
function render(){var saved=api.get(),items=current();list.innerHTML=items.map(card).join("");empty.hidden=saved.length!==0;document.getElementById("bookmarkNoMatch").hidden=saved.length===0||items.length!==0;clearButton.disabled=saved.length===0;count.textContent="저장 "+saved.length+"건 · 표시 "+items.length+"건";live.textContent="즐겨찾기 "+items.length+"건을 표시합니다."}
options(category,data.map(function(b){return b.category}));options(region,data.map(function(b){return b.district||b.region}));var timer;query.addEventListener("input",function(){clearTimeout(timer);timer=setTimeout(render,200)});[sort,category,region].forEach(function(control){control.addEventListener("change",render)});list.addEventListener("click",function(event){var button=event.target.closest("[data-remove-id]");if(button&&api.remove(button.dataset.removeId))render()});clearButton.addEventListener("click",function(){if(api.get().length&&confirm("저장한 즐겨찾기를 모두 삭제할까요?")&&api.clear())render()});document.addEventListener("benefitbookmarkschange",render);render();
}());
