(function(){
"use strict";
var data=Array.isArray(window.BENEFITS_DATA)?window.BENEFITS_DATA:[];
var today=new Date();today.setHours(0,0,0,0);
var params=new URLSearchParams(location.search);
var initialMonth=Number(params.get("month"));
var initialYear=Number(params.get("year"));
var viewDate=new Date(Number.isInteger(initialYear)&&initialYear>2000?initialYear:today.getFullYear(),initialMonth>=1&&initialMonth<=12?initialMonth-1:today.getMonth(),1);
var selectedDate=null;
var categoryAliases={"출산":"출산·육아","노인":"어르신","지역안내":"지역 안내"};
var monthLabel=document.getElementById("calendarMonthLabel"),grid=document.getElementById("calendarGrid"),selectedHeading=document.getElementById("selectedDateHeading"),selectedList=document.getElementById("selectedDateList"),selectedEmpty=document.getElementById("selectedDateEmpty");
var query=document.getElementById("calendarQuery"),category=document.getElementById("calendarCategory"),region=document.getElementById("calendarRegion"),live=document.getElementById("calendarLive");
var ongoingList=document.getElementById("ongoingList"),noticeList=document.getElementById("noticeList"),ongoingEmpty=document.getElementById("ongoingEmpty"),noticeEmpty=document.getElementById("noticeEmpty");

function parseDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||""))return null;var p=value.split("-").map(Number),d=new Date(p[0],p[1]-1,p[2]);return d.getFullYear()===p[0]&&d.getMonth()===p[1]-1&&d.getDate()===p[2]?d:null}
function dateKey(d){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function normalize(v){return String(v||"").toLocaleLowerCase("ko-KR").replace(/\s+/g,"").trim()}
function isOngoing(b){return b.applicationType==="상시"||b.applicationStatus==="상시 신청"}
function isNotice(b){return b.applicationStatus==="공고 확인"}
function monthBounds(){return{start:new Date(viewDate.getFullYear(),viewDate.getMonth(),1),end:new Date(viewDate.getFullYear(),viewDate.getMonth()+1,0)}}
function appliesOn(b,d){var s=parseDate(b.applicationStart),e=parseDate(b.applicationEnd);if(!s&&!e)return false;if(s&&e)return d>=s&&d<=e;if(s)return dateKey(d)===dateKey(s);return dateKey(d)===dateKey(e)}
function filteredData(){var q=normalize(query.value),cat=categoryAliases[category.value]||category.value,reg=region.value;return data.filter(function(b){var text=normalize([b.title,b.region,b.district,(b.keywords||[]).join(" ")].join(" "));return(!q||text.indexOf(q)!==-1)&&(!cat||b.category===cat)&&(!reg||b.region===reg)})}
function updateUrl(){var p=new URLSearchParams();p.set("month",String(viewDate.getMonth()+1));p.set("year",String(viewDate.getFullYear()));if(region.value)p.set("region",region.value);if(category.value)p.set("category",category.value);history.replaceState(null,"",location.pathname+"?"+p.toString())}
function escapeHtml(v){return String(v||"").replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function deadlineBadge(b){var end=parseDate(b.applicationEnd);if(!end)return"";var diff=Math.round((end-today)/86400000);if(diff===0)return'<span class="calendar-deadline today">오늘 마감</span>';if(diff>0&&diff<=7)return'<span class="calendar-deadline soon">마감 예정</span>';return""}
function periodText(b){if(b.applicationStart&&b.applicationEnd)return b.applicationStart+" ~ "+b.applicationEnd;if(b.applicationStart)return b.applicationStart+"부터";if(b.applicationEnd)return b.applicationEnd+"까지";return"공식 공고 확인"}
function card(b){return'<article class="calendar-item"><div class="calendar-item-badges"><span>'+escapeHtml(b.category)+'</span><span>'+escapeHtml(b.district||b.region)+'</span><span>'+escapeHtml(b.applicationStatus||"공고 확인")+'</span>'+deadlineBadge(b)+'</div><h3>'+escapeHtml(b.title)+'</h3><p><strong>신청 기간</strong> '+escapeHtml(periodText(b))+'</p><p>'+escapeHtml(b.summary)+'</p><p class="calendar-official">일정과 자격은 공식 공고에서 다시 확인하세요.</p>'+(b.url?'<a href="'+encodeURI(b.url)+'">자세히 보기</a>':'')+'</article>'}
function renderCards(target,items,empty){target.innerHTML=items.map(card).join("");empty.hidden=items.length!==0}
function summary(items){var bounds=monthBounds();var available=items.filter(function(b){var s=parseDate(b.applicationStart),e=parseDate(b.applicationEnd);return b.applicationStatus==="신청 가능"||(!isOngoing(b)&&((s&&e&&s<=bounds.end&&e>=bounds.start)||(s&&s>=bounds.start&&s<=bounds.end)||(e&&e>=bounds.start&&e<=bounds.end)))}).length;var ending=items.filter(function(b){var e=parseDate(b.applicationEnd);return e&&e>=bounds.start&&e<=bounds.end}).length;document.getElementById("summaryAvailable").textContent=available;document.getElementById("summaryEnding").textContent=ending;document.getElementById("summaryOngoing").textContent=items.filter(isOngoing).length;document.getElementById("summaryNotice").textContent=items.filter(isNotice).length}
function renderSelected(items){var matches=selectedDate?items.filter(function(b){return appliesOn(b,selectedDate)}):[];selectedHeading.textContent=selectedDate?dateKey(selectedDate)+" 신청정보":"날짜를 선택하세요";renderCards(selectedList,matches,selectedEmpty);selectedEmpty.querySelector("p").textContent=selectedDate?"이 날짜에 등록된 신청 일정이 없습니다.":"달력 날짜를 선택하면 등록된 신청정보를 표시합니다."}
function renderCalendar(){var items=filteredData(),year=viewDate.getFullYear(),month=viewDate.getMonth(),first=new Date(year,month,1),last=new Date(year,month+1,0);monthLabel.textContent=year+"년 "+(month+1)+"월";grid.innerHTML="";["일","월","화","수","목","금","토"].forEach(function(x){var h=document.createElement("div");h.className="calendar-weekday";h.textContent=x;grid.appendChild(h)});for(var blank=0;blank<first.getDay();blank++){var e=document.createElement("div");e.className="calendar-blank";e.setAttribute("aria-hidden","true");grid.appendChild(e)}for(var day=1;day<=last.getDate();day++){(function(){var d=new Date(year,month,day),events=items.filter(function(b){return appliesOn(b,d)}),button=document.createElement("button");button.type="button";button.className="calendar-day"+(dateKey(d)===dateKey(today)?" is-today":"")+(selectedDate&&dateKey(d)===dateKey(selectedDate)?" is-selected":"");button.setAttribute("aria-label",(month+1)+"월 "+day+"일, 신청정보 "+events.length+"건");button.innerHTML='<span class="calendar-day-number">'+day+'</span>'+(events.length?'<span class="calendar-dots" aria-hidden="true">'+"●".repeat(Math.min(events.length,3))+'</span><span>'+events.length+'건</span>':'');button.addEventListener("click",function(){selectedDate=d;renderAll();selectedHeading.focus()});grid.appendChild(button)})()}summary(items);renderSelected(items);renderCards(ongoingList,items.filter(isOngoing),ongoingEmpty);renderCards(noticeList,items.filter(isNotice),noticeEmpty);live.textContent=monthLabel.textContent+", 필터 결과 "+items.length+"건";updateUrl()}
function renderAll(){renderCalendar()}
document.getElementById("calendarPrevious").addEventListener("click",function(){viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()-1,1);selectedDate=null;renderAll();monthLabel.focus()});
document.getElementById("calendarNext").addEventListener("click",function(){viewDate=new Date(viewDate.getFullYear(),viewDate.getMonth()+1,1);selectedDate=null;renderAll();monthLabel.focus()});
[category,region].forEach(function(x){x.addEventListener("change",renderAll)});var timer;query.addEventListener("input",function(){clearTimeout(timer);timer=setTimeout(renderAll,200)});
var urlRegion=params.get("region")||"",urlCategory=params.get("category")||"";if(Array.from(region.options).some(function(x){return x.value===urlRegion}))region.value=urlRegion;if(Array.from(category.options).some(function(x){return x.value===urlCategory}))category.value=urlCategory;
window.BenefitCalendar={parseDate:parseDate,isOngoing:isOngoing,isNotice:isNotice,appliesOn:appliesOn,periodText:periodText};renderAll()
}());
