(function(){
"use strict";
var data=Array.isArray(window.BENEFITS_DATA)?window.BENEFITS_DATA:[];
var regions=["서울","경기","인천","부산","대구","광주","대전","울산","세종","강원","충북","충남","전북","전남","경북","경남","제주"];
var categoryWeights={"청년":10,"주거":10,"교육":8,"어르신":8,"출산·육아":8};
var categoryAliases={"출산":"출산·육아","노인":"어르신","지역 안내":"지역 안내"};
var params=new URLSearchParams(location.search),selectedRegion=params.get("region")||"서울";if(regions.indexOf(selectedRegion)===-1)selectedRegion="서울";
var query=document.getElementById("regionQuery"),category=document.getElementById("regionCategory"),grid=document.getElementById("regionGrid"),heading=document.getElementById("regionDetailHeading"),topList=document.getElementById("regionTopList"),districtSection=document.getElementById("seoulDistrictSection"),districtGrid=document.getElementById("seoulDistrictGrid"),nationalList=document.getElementById("nationalTopList"),live=document.getElementById("regionLive"),empty=document.getElementById("regionEmpty");

/* Future extension point for verified clickCount, viewCount or gaPopularity.
   This release returns a neutral score and does not read analytics data. */
function getRegionSignals(){return{score:0,reasons:[]}}
function calculateRegionScore(benefit,region){var score=0,reasons=[];if(benefit.featured){score+=30;reasons.push("대표 지원사업")}if(benefit.region==="전국"){score+=15;reasons.push("전국 공통")}if(benefit.region===region){score+=30;reasons.push(region+" 지역 대표 정보")}if(benefit.url){score+=20;reasons.push("상세 페이지 제공")}var weight=categoryWeights[benefit.category]||0;if(weight){score+=weight;reasons.push(benefit.category+" 분야")}if(benefit.category==="지역 안내")score-=20;var signals=getRegionSignals(benefit,region);score+=signals.score;reasons=reasons.concat(signals.reasons);return{score:score,reasons:reasons.slice(0,4)}}
function normalize(v){return String(v||"").toLocaleLowerCase("ko-KR").replace(/\s+/g,"").trim()}
function text(b){return normalize([b.title,b.region,b.district,b.category,(b.targetGroups||[]).join(" "),(b.keywords||[]).join(" ")].join(" "))}
function matchesFilters(b){var q=normalize(query.value),cat=categoryAliases[category.value]||category.value;return(!q||text(b).indexOf(q)!==-1)&&(!cat||b.category===cat)}
function ranked(items,region){return items.map(function(b){var r=calculateRegionScore(b,region);return{benefit:b,score:r.score,reasons:r.reasons}}).sort(function(a,b){if(b.score!==a.score)return b.score-a.score;if(Boolean(a.benefit.district)!==Boolean(b.benefit.district))return a.benefit.district?1:-1;return a.benefit.title.localeCompare(b.benefit.title,"ko-KR")})}
function escapeHtml(v){return String(v||"").replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function card(item,rank){var b=item.benefit;return'<article class="region-support-card"><div class="region-support-badges"><span>TOP'+rank+'</span><span>'+escapeHtml(b.category)+'</span><span>'+escapeHtml(b.district||b.region)+'</span><span>'+escapeHtml(b.applicationStatus||"공고 확인")+'</span></div><h3>'+escapeHtml(b.title)+'</h3><p>'+escapeHtml(b.summary)+'</p><div class="region-reasons"><strong>추천 이유</strong><ul>'+item.reasons.map(function(r){return'<li>'+escapeHtml(r)+'</li>'}).join("")+'</ul></div>'+(b.url?'<a href="'+encodeURI(b.url)+'">자세히 보기</a>':'')+'</article>'}
function regionCard(region){var local=data.filter(function(b){return b.region===region&&matchesFilters(b)}),commonLocal=local.filter(function(b){return!b.district}),representative=ranked(commonLocal.length?commonLocal:local,region)[0],total=local.length;return'<article class="region-card-item'+(region===selectedRegion?' is-selected':'')+'"><button type="button" data-region="'+escapeHtml(region)+'" aria-pressed="'+(region===selectedRegion)+'"><strong>'+escapeHtml(region)+'</strong><span>등록 지원정보 '+total+'개</span><span>대표: '+escapeHtml(representative?representative.benefit.title:"조건에 맞는 정보 없음")+'</span><em>지역 정보 보기</em></button></article>'}
function renderDistricts(){var districts=data.filter(function(b){return b.region==="서울"&&b.district&&matchesFilters(b)}).sort(function(a,b){return a.district.localeCompare(b.district,"ko-KR")});districtGrid.innerHTML=districts.map(function(b){return'<a href="'+encodeURI(b.url)+'"><strong>'+escapeHtml(b.district)+'</strong><span>'+escapeHtml(b.title)+'</span></a>'}).join("");districtSection.hidden=selectedRegion!=="서울"}
function updateUrl(){var p=new URLSearchParams();p.set("region",selectedRegion);if(category.value)p.set("category",category.value);history.replaceState(null,"",location.pathname+"?"+p.toString())}
function render(){grid.innerHTML=regions.map(regionCard).join("");Array.from(grid.querySelectorAll("button[data-region]")).forEach(function(button){button.addEventListener("click",function(){selectedRegion=button.dataset.region;render();heading.focus()})});var candidates=data.filter(function(b){return b.region===selectedRegion&&matchesFilters(b)}),top=ranked(candidates,selectedRegion).slice(0,5);heading.textContent=selectedRegion+" 대표 지원정보 TOP5";topList.innerHTML=top.map(function(item,i){return card(item,i+1)}).join("");empty.hidden=top.length!==0;var national=ranked(data.filter(function(b){return b.region==="전국"&&matchesFilters(b)}),selectedRegion).slice(0,10);nationalList.innerHTML=national.map(function(item,i){return card(item,i+1)}).join("");renderDistricts();live.textContent=selectedRegion+" 선택, 대표 지원정보 "+top.length+"개";updateUrl()}
category.value=Array.from(category.options).some(function(x){return x.value===(params.get("category")||"")})?(params.get("category")||""):"";category.addEventListener("change",render);var timer;query.addEventListener("input",function(){clearTimeout(timer);timer=setTimeout(render,200)});
window.RegionRecommendations={calculateRegionScore:calculateRegionScore,ranked:ranked,getRegionSignals:getRegionSignals};render()
}());
